# DroneSphere Pre-commit Configuration (Simplified)
# =================================================

repos:
  # Basic file checks only (no Python tools that cause environment issues)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(\.venv/|scripts/.*\.sh).*$'
      - id: end-of-file-fixer
        exclude: '^(\.venv/|scripts/.*\.sh).*$'
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-yaml
        exclude: '^(\.venv/).*$'
      - id: check-toml
        exclude: '^(\.venv/).*$'
      - id: check-merge-conflict

# Note: Python formatting (Black/Ruff) available via ./scripts/format-code.sh
# This avoids virtual environment conflicts in pre-commit hooks
