# mkdocs.yml
# ===========================================

site_name: DroneSphere Documentation
site_description: Scalable drone command and control system
site_author: DroneSphere Team
site_url: https://yourusername.github.io/dronesphere

repo_name: yourusername/dronesphere
repo_url: https://github.com/yourusername/dronesphere
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2
  - swagger-ui-tag

nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference: api.md
  - Command Schema: command-schema.md
  - Development:
    - Setup: development/setup.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
  - Deployment: deployment.md
