# agent/config/agent.yaml
# Default configuration for DroneSphere Agent

# Server connection settings
server_url: ws://localhost:8000/ws/agent
server_reconnect_interval: 5

# MAVSDK connection settings
mavsdk_server_address: udp://:14540  # Default for SITL
mavsdk_server_port: 50051  # For future gRPC support

# Drone identification
drone_id: drone_001
drone_name: SITL Alpha

# Telemetry settings
telemetry_rate: 10  # Hz
telemetry_buffer_size: 100

# Safety limits
max_altitude: 50.0  # meters
max_speed: 15.0  # m/s
min_battery_percent: 20.0
geofence_radius: 500.0  # meters

# Command execution
command_timeout: 30  # seconds
command_retry_attempts: 3

# Logging
log_level: INFO
log_file: null  # Set to path for file logging
