# shared/commands/navigation/goto.yaml - Enhanced with speed control
apiVersion: v1
kind: DroneCommand
metadata:
  name: goto
  version: 1.1.0
  category: navigation
  tags: [navigation, offboard, local, velocity-controlled]
spec:
  description:
    brief: "Fly to local NED coordinates with velocity control"
    detailed: |
      Commands the drone to fly to specified local NED (North, East, Down) coordinates
      using MAVSDK offboard mode with configurable speed control and movement verification.
      
      Enhanced Features:
      - Real position verification using mavlink2rest
      - Configurable maximum speed and approach speed
      - Movement detection to verify drone actually moves
      - Detailed progress logging
      
      Coordinate system:
      - North: positive values = north direction (meters)
      - East: positive values = east direction (meters)  
      - Down: negative values = altitude (e.g., down=-5 = 5m altitude)
      - Yaw: heading in degrees (0 = north)
      
      Safety considerations:
      - Drone must be flying before executing goto
      - Uses offboard mode for precise positioning
      - Speed limits prevent aggressive movements
      - Position tolerance checking for completion
      - Movement verification detects if drone actually moves
  parameters:
    north:
      type: float
      default: 0.0
      constraints:
        min: -1000.0
        max: 1000.0
        unit: "m"
      description: "North coordinate in meters (positive = north)"
    east:
      type: float
      default: 0.0
      constraints:
        min: -1000.0
        max: 1000.0
        unit: "m"
      description: "East coordinate in meters (positive = east)"
    down:
      type: float
      default: -5.0
      constraints:
        min: -100.0
        max: 10.0
        unit: "m"
      description: "Down coordinate in meters (negative = altitude, e.g., -5 = 5m high)"
    yaw:
      type: float
      default: 0.0
      constraints:
        min: -180.0
        max: 180.0
        unit: "deg"
      description: "Target heading in degrees (0 = north, 90 = east)"
    tolerance:
      type: float
      default: 2.0
      constraints:
        min: 0.5
        max: 10.0
        unit: "m"
      description: "Position tolerance for completion (meters)"
    timeout:
      type: float
      default: 60.0
      constraints:
        min: 10.0
        max: 300.0
        unit: "s"
      description: "Maximum time to wait for position reached"
    max_speed:
      type: float
      default: 2.0
      constraints:
        min: 0.5
        max: 10.0
        unit: "m/s"
      description: "Maximum horizontal speed during movement"
    approach_speed:
      type: float
      default: 0.5
      constraints:
        min: 0.1
        max: 2.0
        unit: "m/s"
      description: "Speed when approaching target (for precision)"
  implementation:
    handler: "dronesphere.commands.navigation.goto.GotoCommand"
    supported_backends: ["mavsdk"]
    timeout: 90
  telemetry_feedback:
    start: "Flying to position N:{north}m E:{east}m D:{down}m at max {max_speed}m/s..."
    success: "Reached target position within {tolerance}m"
    error: "Goto failed: {error}"