apiVersion: v1
kind: DroneCommand
metadata:
  category: navigation
  critical: false
  max_retries: 0
  name: goto
  tags:
  - navigation
  - offboard
  - local
  - velocity-controlled
  - dual-mode
  timeout_behavior: continue
  version: 2.0.0
spec:
  description:
    brief: Fly to local NED coordinates with absolute or relative positioning
    detailed: "Commands the drone to fly to specified local NED (North, East, Down)\
      \ coordinates\nusing MAVSDK offboard mode with configurable speed control and\
      \ positioning modes.\n\nPOSITIONING MODES:\n1. ABSOLUTE (default): Coordinates\
      \ relative to takeoff origin\n   Example: goto(north=10, east=5, down=-3) \u2192\
      \ \"fly to (10,5,-3) from origin\"\n\n2. RELATIVE: Movement delta from current\
      \ position  \n   Example: goto(north=5, east=0, down=-2, relative=True) \u2192\
      \ \"move 5m north, 2m up from here\"\n\nEnhanced Features:\n- Dual positioning\
      \ modes (absolute/relative)\n- Real position verification using MAVSDK position_velocity_ned()\n\
      - Configurable maximum speed and approach speed\n- Movement detection to verify\
      \ drone actually moves\n- Detailed progress logging and telemetry feedback\n\
      \nCoordinate System (NED):\n- North: positive values = north direction (meters)\n\
      - East: positive values = east direction (meters)  \n- Down: negative values\
      \ = altitude (e.g., down=-5 = 5m altitude)\n- Yaw: heading in degrees (0 = north,\
      \ 90 = east)\n\nSafety Features:\n- Drone must be flying before executing goto\n\
      - Uses offboard mode for precise positioning\n- Speed limits prevent aggressive\
      \ movements\n- Position tolerance checking for completion\n- Movement verification\
      \ detects if drone actually moves\n- Automatic fallback to hold if position\
      \ unavailable\n"
  implementation:
    handler: dronesphere.commands.navigation.goto.GotoCommand
    supported_backends:
    - mavsdk
    timeout: 90
  parameters:
    approach_speed:
      constraints:
        max: 2.0
        min: 0.1
        unit: m/s
      default: 0.5
      description: Speed when approaching target (for precision)
      type: float
    down:
      constraints:
        max: 10.0
        min: -100.0
        unit: m
      default: -5.0
      description: Down coordinate/delta in meters (negative = altitude, e.g., -5
        = 5m high)
      type: float
    east:
      constraints:
        max: 1000.0
        min: -1000.0
        unit: m
      default: 0.0
      description: East coordinate/delta in meters (positive = east direction)
      type: float
    max_speed:
      constraints:
        max: 10.0
        min: 0.5
        unit: m/s
      default: 2.0
      description: Maximum horizontal speed during movement
      type: float
    north:
      constraints:
        max: 1000.0
        min: -1000.0
        unit: m
      default: 0.0
      description: North coordinate/delta in meters (positive = north direction)
      type: float
    relative:
      default: false
      description: 'Positioning mode: false = absolute coordinates, true = relative
        movement from current position'
      type: bool
    timeout:
      constraints:
        max: 300.0
        min: 10.0
        unit: s
      default: 60.0
      description: Maximum time to wait for position reached
      type: float
    tolerance:
      constraints:
        max: 10.0
        min: 0.5
        unit: m
      default: 2.0
      description: Position tolerance for completion (meters)
      type: float
    yaw:
      constraints:
        max: 180.0
        min: -180.0
        unit: deg
      default: 0.0
      description: Target heading in degrees (0 = north, 90 = east)
      type: float
  telemetry_feedback:
    error: 'Goto failed: {error}'
    start: Flying to {mode} position N:{north}m E:{east}m D:{down}m at max {max_speed}m/s...
    success: Reached target position within {tolerance}m
