apiVersion: v1
kind: DroneCommand
metadata:
  category: patterns
  critical: false
  max_retries: 0
  name: circle
  tags:
  - advanced
  - patterns
  - autonomous
  timeout_behavior: continue
  version: 1.0.0
spec:
  description:
    brief: Fly in circular pattern
    detailed: 'Commands the drone to fly in a circular pattern around the current
      position

      or a specified center point.

      '
  implementation:
    handler: dronesphere.commands.circle.CircleCommand
    supported_backends:
    - mavsdk
    timeout: 300
  parameters:
    clockwise:
      default: true
      description: Direction of rotation (true for clockwise)
      type: bool
    radius:
      constraints:
        max: 100.0
        min: 5.0
        unit: m
      default: 10.0
      description: Circle radius in meters
      type: float
    speed:
      constraints:
        max: 15.0
        min: 1.0
        unit: m/s
      default: 5.0
      description: Flight speed in meters per second
      type: float
    turns:
      constraints:
        max: 10.0
        min: 0.25
        unit: revolutions
      default: 1.0
      description: Number of complete turns to make
      type: float
  telemetry_feedback:
    error: 'Circle pattern failed: {error}'
    start: Starting circular pattern with radius {radius}m
    success: Completed circular pattern
