# shared/config/ai.yaml
# ===================================
# AI/LLM configuration for future expansion

ai:
  enabled: false
  
  llm:
    provider: "openai"  # openai, anthropic, local
    model: "gpt-4"
    max_tokens: 1000
    temperature: 0.1
    
  natural_language:
    enabled: false
    supported_languages: ["en", "es", "fr"]
    intent_confidence_threshold: 0.8
    
  mission_planning:
    enabled: false
    optimization_algorithm: "genetic"
    consider_weather: true
    consider_traffic: true
    
  computer_vision:
    enabled: false
    object_detection: false
    obstacle_avoidance: false
    landing_assistance: false
