# shared/config/logging.yaml
# ===================================
# Logging configuration

logging:
  level: "INFO"
  format: "json"  # json, text
  
  outputs:
    console:
      enabled: true
      level: "INFO"
      
    file:
      enabled: false  # Future expansion
      path: "/var/log/dronesphere"
      rotation: "daily"
      retention_days: 7
      
    remote:
      enabled: false  # Future: centralized logging
      endpoint: null
      api_key: null
      
  structured_fields:
    - "timestamp"
    - "level"
    - "logger"
    - "message"
    - "drone_id"
    - "command_id"
    - "correlation_id"