# docker/monitoring/prometheus.yml
# ===================================
# Prometheus configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dronesphere-server'
    static_configs:
      - targets: ['server:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'dronesphere-agent'
    static_configs:
      - targets: ['agent:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s
