# shared/config/sitl.yaml
# ===================================
# SITL-specific configuration

sitl:
  px4:
    model: "iris"  # PX4 vehicle model
    world: "empty"  # Gazebo world
    headless: true
    debugger: false
    lockstep: true
  
  gazebo:
    physics_engine: "ode"
    real_time_factor: 1.0
    step_size: 0.001
  
  mavlink:
    system_id: 1
    component_id: 1
    udp_port: 14540
    tcp_port: 4560
  
  environment:
    wind_speed: 0.0
    wind_direction: 0.0
    temperature: 20.0
    pressure: 1013.25