apiVersion: v1
kind: DroneCommand
metadata:
  name: land
  version: 1.0.0
  category: flight
  tags: [basic, flight]
spec:
  description:
    brief: "Land the drone"
    detailed: |
      Commands the drone to land at its current position.
      The drone will descend and disarm once it touches the ground.
  parameters:
    timeout:
      type: float
      default: 30.0
      constraints:
        min: 10.0
        max: 120.0
        unit: "s"
      description: "Maximum time to wait for landing completion"
    precision_land:
      type: bool
      default: false
      description: "Use precision landing if available"
  implementation:
    handler: "dronesphere.commands.basic.land.LandCommand"
    supported_backends: ["mavsdk"]
    timeout: 60
  telemetry_feedback:
    start: "Landing drone..."
    success: "Landing completed successfully"
    error: "Landing failed: {error}"
