apiVersion: v1
kind: DroneCommand
metadata:
  name: takeoff
  version: 1.0.0
  category: flight
  tags: [basic, flight]
spec:
  description:
    brief: "Take off to specified altitude"
    detailed: |
      Commands the drone to arm and take off to the specified altitude.
      The drone will hover at the target altitude until the next command.
  parameters:
    altitude:
      type: float
      default: 10.0
      constraints:
        min: 1.0
        max: 50.0
        unit: "m"
      description: "Target altitude in meters above ground level"
    altitude_tolerance:
      type: float
      default: 1.0
      constraints:
        min: 0.1
        max: 5.0
      description: "Altitude tolerance (fraction of target altitude to accept as success)"
    timeout:
      type: float
      default: 20.0
      constraints:
        min: 5.0
        max: 60.0
        unit: "s"
      description: "Maximum time to wait for takeoff completion"
  implementation:
    handler: "dronesphere.commands.basic.takeoff.TakeoffCommand"
    supported_backends: ["mavsdk"]
    timeout: 60
  telemetry_feedback:
    start: "Taking off to {altitude} meters..."
    success: "Successfully reached {altitude} meters"
    error: "Takeoff failed: {error}"
