# shared/commands/basic/takeoff.yaml
apiVersion: v1
kind: DroneCommand
metadata:
  name: takeoff
  category: flight
  tags: ["basic", "vertical", "movement"]
  version: "1.0.0"

spec:
  description:
    brief: "Take off to specified altitude"
    detailed: |
      Arms the drone (if not already armed) and performs a vertical
      takeoff to the specified altitude. The drone will hover at the
      target altitude once reached.
    examples:
      - text: "Take off to 20 meters"
        params:
          altitude: 20
      - text: "Launch the drone to 50 feet"
        params:
          altitude: 15.24  # 50 feet in meters
      - text: "برخیز به ارتفاع ۱۰ متر"
        params:
          altitude: 10
        language: fa
      - text: "پرواز کن"
        params:
          altitude: 10  # default
        language: fa

  parameters:
    altitude:
      type: float
      required: true
      default: 10.0
      constraints:
        min: 1.0
        max: 50.0  # Safety limit for testing
        unit: meters
      description: "Target altitude above takeoff point"

  implementation:
    handler: "basic_commands.TakeoffCommand"
    supported_backends: ["mavsdk", "pymavlink"]
    timeout: 30

  safety:
    pre_checks:
      - battery_min: 30
      - gps_fix: true
      - clear_above: true
    emergency_action: "land"

  telemetry_feedback:
    start: "Taking off to {altitude} meters"
    progress: "Current altitude: {current_altitude}m"
    success: "Reached target altitude of {altitude} meters"
    failure: "Takeoff failed: {error}"
